# Generated by Django 3.2.7 on 2021-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Fear_Greed', models.DateField()),
                ('Fear_Greed', models.IntegerField()),
                ('Daily_NYSE', models.DateField()),
                ('NYSE_Up_Vol', models.IntegerField()),
                ('Daily_Riskapp', models.DateField()),
                ('Risk_App', models.IntegerField()),
                ('Weekly_Bull', models.DateField()),
                ('Bull_ratio', models.IntegerField()),
                ('Daily_putcall', models.DateField()),
                ('Put_Call', models.IntegerField()),
            ],
        ),
    ]
