# Generated by Django 3.2.7 on 2021-10-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='Bull_ratio',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Daily_Fear_Greed',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Daily_NYSE',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Daily_Riskapp',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Daily_putcall',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Fear_Greed',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='NYSE_Up_Vol',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Put_Call',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Risk_App',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Weekly_Bull',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='datatable',
            table='datatable',
        ),
    ]
