# Generated by Django 3.2.7 on 2021-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211015_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='Bull_ratio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Fear_Greed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='NYSE_Up_Vol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Put_Call',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Risk_App',
            field=models.IntegerField(),
        ),
    ]
