# Generated by Django 3.2.7 on 2021-10-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211015_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='bullratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weekly_Bull', models.DateField(max_length=200)),
                ('Bull_ratio', models.IntegerField()),
            ],
            options={
                'db_table': 'bullratio',
            },
        ),
        migrations.CreateModel(
            name='feargreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Fear_Greed', models.DateField(max_length=200)),
                ('Fear_Greed', models.IntegerField()),
            ],
            options={
                'db_table': 'feargreed',
            },
        ),
        migrations.CreateModel(
            name='nyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_NYSE', models.DateField(max_length=200)),
                ('NYSE_Up_Vol', models.IntegerField()),
            ],
            options={
                'db_table': 'nyse',
            },
        ),
        migrations.CreateModel(
            name='putcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_putcall', models.DateField(max_length=200)),
                ('Put_Call', models.IntegerField()),
            ],
            options={
                'db_table': 'putcall',
            },
        ),
        migrations.CreateModel(
            name='riskapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Riskapp', models.DateField(max_length=200)),
                ('Risk_App', models.IntegerField()),
            ],
            options={
                'db_table': 'riskapp',
            },
        ),
        migrations.DeleteModel(
            name='datatable',
        ),
    ]
