# Generated by Django 3.2.7 on 2021-10-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20211015_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullratio',
            name='Bull_ratio',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='feargreed',
            name='Fear_Greed',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='nyse',
            name='NYSE_Up_Vol',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='putcall',
            name='Put_Call',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
        migrations.AlterField(
            model_name='riskapp',
            name='Risk_App',
            field=models.DecimalField(decimal_places=20, max_digits=25),
        ),
    ]
