# Generated by Django 3.2.7 on 2021-10-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20211019_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bullratio',
        ),
        migrations.DeleteModel(
            name='feargreed',
        ),
        migrations.DeleteModel(
            name='nyse',
        ),
        migrations.DeleteModel(
            name='putcall',
        ),
    ]
