# Generated by Django 3.2.7 on 2021-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20211022_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='bullratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weekly_Bull', models.DateField(max_length=200)),
                ('Bull_ratio', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
            options={
                'db_table': 'bullratio',
            },
        ),
        migrations.CreateModel(
            name='feargreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_Fear_Greed', models.DateField(max_length=200)),
                ('Fear_Greed', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
            options={
                'db_table': 'feargreed',
            },
        ),
        migrations.CreateModel(
            name='nyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_NYSE', models.DateField(max_length=200)),
                ('NYSE_Up_Vol', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
            options={
                'db_table': 'nyse',
            },
        ),
        migrations.CreateModel(
            name='putcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Daily_putcall', models.DateField(max_length=200)),
                ('Put_Call', models.DecimalField(decimal_places=20, max_digits=25)),
            ],
            options={
                'db_table': 'putcall',
            },
        ),
    ]
